// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storepb/store.proto

package storepb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StoreRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreRequest) Reset()         { *m = StoreRequest{} }
func (m *StoreRequest) String() string { return proto.CompactTextString(m) }
func (*StoreRequest) ProtoMessage()    {}
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7568ae88fa351714, []int{0}
}

func (m *StoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreRequest.Unmarshal(m, b)
}
func (m *StoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreRequest.Marshal(b, m, deterministic)
}
func (m *StoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreRequest.Merge(m, src)
}
func (m *StoreRequest) XXX_Size() int {
	return xxx_messageInfo_StoreRequest.Size(m)
}
func (m *StoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StoreRequest proto.InternalMessageInfo

func (m *StoreRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *StoreRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type StoreResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreResponse) Reset()         { *m = StoreResponse{} }
func (m *StoreResponse) String() string { return proto.CompactTextString(m) }
func (*StoreResponse) ProtoMessage()    {}
func (*StoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7568ae88fa351714, []int{1}
}

func (m *StoreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreResponse.Unmarshal(m, b)
}
func (m *StoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreResponse.Marshal(b, m, deterministic)
}
func (m *StoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreResponse.Merge(m, src)
}
func (m *StoreResponse) XXX_Size() int {
	return xxx_messageInfo_StoreResponse.Size(m)
}
func (m *StoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StoreResponse proto.InternalMessageInfo

func (m *StoreResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type RemoveRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveRequest) Reset()         { *m = RemoveRequest{} }
func (m *RemoveRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveRequest) ProtoMessage()    {}
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7568ae88fa351714, []int{2}
}

func (m *RemoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveRequest.Unmarshal(m, b)
}
func (m *RemoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveRequest.Marshal(b, m, deterministic)
}
func (m *RemoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveRequest.Merge(m, src)
}
func (m *RemoveRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveRequest.Size(m)
}
func (m *RemoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveRequest proto.InternalMessageInfo

func (m *RemoveRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *RemoveRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type RemoveResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveResponse) Reset()         { *m = RemoveResponse{} }
func (m *RemoveResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveResponse) ProtoMessage()    {}
func (*RemoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7568ae88fa351714, []int{3}
}

func (m *RemoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveResponse.Unmarshal(m, b)
}
func (m *RemoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveResponse.Marshal(b, m, deterministic)
}
func (m *RemoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveResponse.Merge(m, src)
}
func (m *RemoveResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveResponse.Size(m)
}
func (m *RemoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveResponse proto.InternalMessageInfo

func (m *RemoveResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type GetVRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVRequest) Reset()         { *m = GetVRequest{} }
func (m *GetVRequest) String() string { return proto.CompactTextString(m) }
func (*GetVRequest) ProtoMessage()    {}
func (*GetVRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7568ae88fa351714, []int{4}
}

func (m *GetVRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVRequest.Unmarshal(m, b)
}
func (m *GetVRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVRequest.Marshal(b, m, deterministic)
}
func (m *GetVRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVRequest.Merge(m, src)
}
func (m *GetVRequest) XXX_Size() int {
	return xxx_messageInfo_GetVRequest.Size(m)
}
func (m *GetVRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVRequest proto.InternalMessageInfo

func (m *GetVRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetVResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVResponse) Reset()         { *m = GetVResponse{} }
func (m *GetVResponse) String() string { return proto.CompactTextString(m) }
func (*GetVResponse) ProtoMessage()    {}
func (*GetVResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7568ae88fa351714, []int{5}
}

func (m *GetVResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVResponse.Unmarshal(m, b)
}
func (m *GetVResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVResponse.Marshal(b, m, deterministic)
}
func (m *GetVResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVResponse.Merge(m, src)
}
func (m *GetVResponse) XXX_Size() int {
	return xxx_messageInfo_GetVResponse.Size(m)
}
func (m *GetVResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVResponse proto.InternalMessageInfo

func (m *GetVResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type GetKRequest struct {
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetKRequest) Reset()         { *m = GetKRequest{} }
func (m *GetKRequest) String() string { return proto.CompactTextString(m) }
func (*GetKRequest) ProtoMessage()    {}
func (*GetKRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7568ae88fa351714, []int{6}
}

func (m *GetKRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetKRequest.Unmarshal(m, b)
}
func (m *GetKRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetKRequest.Marshal(b, m, deterministic)
}
func (m *GetKRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetKRequest.Merge(m, src)
}
func (m *GetKRequest) XXX_Size() int {
	return xxx_messageInfo_GetKRequest.Size(m)
}
func (m *GetKRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetKRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetKRequest proto.InternalMessageInfo

func (m *GetKRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type GetKResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetKResponse) Reset()         { *m = GetKResponse{} }
func (m *GetKResponse) String() string { return proto.CompactTextString(m) }
func (*GetKResponse) ProtoMessage()    {}
func (*GetKResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7568ae88fa351714, []int{7}
}

func (m *GetKResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetKResponse.Unmarshal(m, b)
}
func (m *GetKResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetKResponse.Marshal(b, m, deterministic)
}
func (m *GetKResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetKResponse.Merge(m, src)
}
func (m *GetKResponse) XXX_Size() int {
	return xxx_messageInfo_GetKResponse.Size(m)
}
func (m *GetKResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetKResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetKResponse proto.InternalMessageInfo

func (m *GetKResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type RemoveAllRequest struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveAllRequest) Reset()         { *m = RemoveAllRequest{} }
func (m *RemoveAllRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveAllRequest) ProtoMessage()    {}
func (*RemoveAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7568ae88fa351714, []int{8}
}

func (m *RemoveAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveAllRequest.Unmarshal(m, b)
}
func (m *RemoveAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveAllRequest.Marshal(b, m, deterministic)
}
func (m *RemoveAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveAllRequest.Merge(m, src)
}
func (m *RemoveAllRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveAllRequest.Size(m)
}
func (m *RemoveAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveAllRequest proto.InternalMessageInfo

func (m *RemoveAllRequest) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type RemoveAllResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveAllResponse) Reset()         { *m = RemoveAllResponse{} }
func (m *RemoveAllResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveAllResponse) ProtoMessage()    {}
func (*RemoveAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7568ae88fa351714, []int{9}
}

func (m *RemoveAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveAllResponse.Unmarshal(m, b)
}
func (m *RemoveAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveAllResponse.Marshal(b, m, deterministic)
}
func (m *RemoveAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveAllResponse.Merge(m, src)
}
func (m *RemoveAllResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveAllResponse.Size(m)
}
func (m *RemoveAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveAllResponse proto.InternalMessageInfo

func (m *RemoveAllResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type StoreCsvRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreCsvRequest) Reset()         { *m = StoreCsvRequest{} }
func (m *StoreCsvRequest) String() string { return proto.CompactTextString(m) }
func (*StoreCsvRequest) ProtoMessage()    {}
func (*StoreCsvRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7568ae88fa351714, []int{10}
}

func (m *StoreCsvRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreCsvRequest.Unmarshal(m, b)
}
func (m *StoreCsvRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreCsvRequest.Marshal(b, m, deterministic)
}
func (m *StoreCsvRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreCsvRequest.Merge(m, src)
}
func (m *StoreCsvRequest) XXX_Size() int {
	return xxx_messageInfo_StoreCsvRequest.Size(m)
}
func (m *StoreCsvRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreCsvRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StoreCsvRequest proto.InternalMessageInfo

func (m *StoreCsvRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *StoreCsvRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type StoreCsvResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreCsvResponse) Reset()         { *m = StoreCsvResponse{} }
func (m *StoreCsvResponse) String() string { return proto.CompactTextString(m) }
func (*StoreCsvResponse) ProtoMessage()    {}
func (*StoreCsvResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7568ae88fa351714, []int{11}
}

func (m *StoreCsvResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreCsvResponse.Unmarshal(m, b)
}
func (m *StoreCsvResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreCsvResponse.Marshal(b, m, deterministic)
}
func (m *StoreCsvResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreCsvResponse.Merge(m, src)
}
func (m *StoreCsvResponse) XXX_Size() int {
	return xxx_messageInfo_StoreCsvResponse.Size(m)
}
func (m *StoreCsvResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreCsvResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StoreCsvResponse proto.InternalMessageInfo

func (m *StoreCsvResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type RemoveCsvRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveCsvRequest) Reset()         { *m = RemoveCsvRequest{} }
func (m *RemoveCsvRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveCsvRequest) ProtoMessage()    {}
func (*RemoveCsvRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7568ae88fa351714, []int{12}
}

func (m *RemoveCsvRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveCsvRequest.Unmarshal(m, b)
}
func (m *RemoveCsvRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveCsvRequest.Marshal(b, m, deterministic)
}
func (m *RemoveCsvRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveCsvRequest.Merge(m, src)
}
func (m *RemoveCsvRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveCsvRequest.Size(m)
}
func (m *RemoveCsvRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveCsvRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveCsvRequest proto.InternalMessageInfo

func (m *RemoveCsvRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *RemoveCsvRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type RemoveCsvResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveCsvResponse) Reset()         { *m = RemoveCsvResponse{} }
func (m *RemoveCsvResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveCsvResponse) ProtoMessage()    {}
func (*RemoveCsvResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7568ae88fa351714, []int{13}
}

func (m *RemoveCsvResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveCsvResponse.Unmarshal(m, b)
}
func (m *RemoveCsvResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveCsvResponse.Marshal(b, m, deterministic)
}
func (m *RemoveCsvResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveCsvResponse.Merge(m, src)
}
func (m *RemoveCsvResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveCsvResponse.Size(m)
}
func (m *RemoveCsvResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveCsvResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveCsvResponse proto.InternalMessageInfo

func (m *RemoveCsvResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type GetAllRequest struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllRequest) Reset()         { *m = GetAllRequest{} }
func (m *GetAllRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllRequest) ProtoMessage()    {}
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7568ae88fa351714, []int{14}
}

func (m *GetAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllRequest.Unmarshal(m, b)
}
func (m *GetAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllRequest.Marshal(b, m, deterministic)
}
func (m *GetAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllRequest.Merge(m, src)
}
func (m *GetAllRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllRequest.Size(m)
}
func (m *GetAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllRequest proto.InternalMessageInfo

func (m *GetAllRequest) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GetAllResponse struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllResponse) Reset()         { *m = GetAllResponse{} }
func (m *GetAllResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllResponse) ProtoMessage()    {}
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7568ae88fa351714, []int{15}
}

func (m *GetAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllResponse.Unmarshal(m, b)
}
func (m *GetAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllResponse.Marshal(b, m, deterministic)
}
func (m *GetAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllResponse.Merge(m, src)
}
func (m *GetAllResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllResponse.Size(m)
}
func (m *GetAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllResponse proto.InternalMessageInfo

func (m *GetAllResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetAllResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*StoreRequest)(nil), "store.StoreRequest")
	proto.RegisterType((*StoreResponse)(nil), "store.StoreResponse")
	proto.RegisterType((*RemoveRequest)(nil), "store.RemoveRequest")
	proto.RegisterType((*RemoveResponse)(nil), "store.RemoveResponse")
	proto.RegisterType((*GetVRequest)(nil), "store.GetVRequest")
	proto.RegisterType((*GetVResponse)(nil), "store.GetVResponse")
	proto.RegisterType((*GetKRequest)(nil), "store.GetKRequest")
	proto.RegisterType((*GetKResponse)(nil), "store.GetKResponse")
	proto.RegisterType((*RemoveAllRequest)(nil), "store.RemoveAllRequest")
	proto.RegisterType((*RemoveAllResponse)(nil), "store.RemoveAllResponse")
	proto.RegisterType((*StoreCsvRequest)(nil), "store.StoreCsvRequest")
	proto.RegisterType((*StoreCsvResponse)(nil), "store.StoreCsvResponse")
	proto.RegisterType((*RemoveCsvRequest)(nil), "store.RemoveCsvRequest")
	proto.RegisterType((*RemoveCsvResponse)(nil), "store.RemoveCsvResponse")
	proto.RegisterType((*GetAllRequest)(nil), "store.GetAllRequest")
	proto.RegisterType((*GetAllResponse)(nil), "store.GetAllResponse")
}

func init() { proto.RegisterFile("storepb/store.proto", fileDescriptor_7568ae88fa351714) }

var fileDescriptor_7568ae88fa351714 = []byte{
	// 396 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0xa5, 0x22, 0x55, 0x46, 0x40, 0x5c, 0x10, 0x9a, 0x5e, 0xd4, 0xd5, 0x28, 0xd1, 0x04, 0x3f,
	0x23, 0xe2, 0x45, 0xc5, 0x03, 0x87, 0xde, 0x20, 0xf1, 0xe0, 0x4d, 0xcc, 0x86, 0x18, 0x8b, 0xc5,
	0x6e, 0x69, 0xe2, 0x0f, 0xf6, 0x7f, 0x98, 0xee, 0x47, 0xd9, 0xa5, 0x68, 0xc1, 0x53, 0x77, 0x66,
	0xe7, 0xbd, 0x79, 0x3b, 0xfb, 0xba, 0x50, 0xa1, 0x81, 0xe7, 0x93, 0xf1, 0xe0, 0x94, 0x7d, 0x9b,
	0x63, 0xdf, 0x0b, 0x3c, 0x94, 0x63, 0x01, 0xbe, 0x86, 0x42, 0x3f, 0x5a, 0xf4, 0xc8, 0xe7, 0x84,
	0xd0, 0x00, 0x95, 0x21, 0xfb, 0x4e, 0xbe, 0x2c, 0x63, 0xd7, 0x68, 0xe4, 0x7b, 0xd1, 0x12, 0x55,
	0x21, 0x17, 0xbe, 0xb8, 0x13, 0x62, 0xad, 0xb0, 0x1c, 0x0f, 0xf0, 0x11, 0x14, 0x05, 0x8e, 0x8e,
	0xbd, 0x0f, 0x4a, 0x50, 0x0d, 0x4c, 0x9f, 0xd0, 0x89, 0x1b, 0x08, 0xac, 0x88, 0x70, 0x0b, 0x8a,
	0x3d, 0x32, 0xf2, 0xc2, 0xa5, 0x3b, 0x34, 0xa0, 0x24, 0x81, 0x29, 0x2d, 0x76, 0x60, 0xa3, 0x4b,
	0x82, 0xa7, 0x5f, 0x1b, 0xe0, 0x43, 0x28, 0xf0, 0x82, 0x14, 0xa2, 0x7d, 0x46, 0xe4, 0x48, 0xa2,
	0xf9, 0xba, 0x38, 0x99, 0x93, 0x4a, 0x76, 0x00, 0x65, 0xae, 0xff, 0xc1, 0x75, 0x15, 0x69, 0x23,
	0x3a, 0x94, 0xd2, 0x46, 0x74, 0x88, 0x4f, 0x60, 0x4b, 0xa9, 0x4a, 0xa1, 0x6c, 0xc3, 0x26, 0x1b,
	0xfa, 0x23, 0x0d, 0x97, 0x9d, 0xe6, 0x31, 0x94, 0xa7, 0xd0, 0x94, 0x36, 0xb7, 0x52, 0xf9, 0x3f,
	0xfa, 0xc4, 0xe7, 0x59, 0xa4, 0xd1, 0x1e, 0x14, 0xbb, 0x24, 0xf8, 0x73, 0x3e, 0x37, 0x50, 0x92,
	0x25, 0x82, 0x6c, 0x41, 0x25, 0x17, 0xdf, 0x59, 0x61, 0xed, 0x3e, 0xf1, 0xc3, 0xb7, 0x57, 0x82,
	0xae, 0x20, 0xc7, 0x62, 0x54, 0x69, 0xf2, 0x1f, 0x41, 0x35, 0xbe, 0x5d, 0xd5, 0x93, 0xbc, 0x19,
	0xce, 0xa0, 0x16, 0x98, 0xfc, 0x40, 0x48, 0x56, 0x68, 0x76, 0xb6, 0xb7, 0x67, 0xb2, 0x31, 0xf0,
	0x1c, 0x56, 0x23, 0xd3, 0x21, 0x24, 0x0a, 0x14, 0x8b, 0xda, 0x15, 0x2d, 0x37, 0x03, 0x71, 0x54,
	0x88, 0x33, 0x07, 0xe2, 0x28, 0x90, 0x7b, 0xc8, 0xc7, 0xfe, 0x41, 0x75, 0x4d, 0xcb, 0x74, 0xae,
	0xb6, 0x95, 0xdc, 0x88, 0x19, 0xee, 0x60, 0x5d, 0x3a, 0x03, 0xd5, 0xd4, 0x21, 0x4c, 0x6f, 0xdf,
	0xae, 0x27, 0xf2, 0x12, 0xde, 0x30, 0x50, 0x47, 0x4a, 0x88, 0x18, 0x74, 0x09, 0x0a, 0x85, 0x95,
	0xdc, 0x50, 0x38, 0xda, 0x60, 0xf2, 0x6b, 0x8e, 0xa7, 0xac, 0x19, 0x23, 0x9e, 0xb2, 0xee, 0x05,
	0x9c, 0x39, 0x33, 0x3a, 0xf9, 0xe7, 0x35, 0xf1, 0xbe, 0x0d, 0x4c, 0xf6, 0xb4, 0x5d, 0xfe, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x46, 0x7c, 0x82, 0xea, 0xf1, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StoreServiceClient is the client API for StoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StoreServiceClient interface {
	// Unary
	Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error)
	Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error)
	GetV(ctx context.Context, in *GetVRequest, opts ...grpc.CallOption) (*GetVResponse, error)
	GetK(ctx context.Context, in *GetKRequest, opts ...grpc.CallOption) (*GetKResponse, error)
	RemoveAll(ctx context.Context, in *RemoveAllRequest, opts ...grpc.CallOption) (*RemoveAllResponse, error)
	// client streaming
	StoreCsv(ctx context.Context, opts ...grpc.CallOption) (StoreService_StoreCsvClient, error)
	RemoveCsv(ctx context.Context, opts ...grpc.CallOption) (StoreService_RemoveCsvClient, error)
	// server streaming
	GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (StoreService_GetAllClient, error)
}

type storeServiceClient struct {
	cc *grpc.ClientConn
}

func NewStoreServiceClient(cc *grpc.ClientConn) StoreServiceClient {
	return &storeServiceClient{cc}
}

func (c *storeServiceClient) Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error) {
	out := new(StoreResponse)
	err := c.cc.Invoke(ctx, "/store.StoreService/Store", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error) {
	out := new(RemoveResponse)
	err := c.cc.Invoke(ctx, "/store.StoreService/Remove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) GetV(ctx context.Context, in *GetVRequest, opts ...grpc.CallOption) (*GetVResponse, error) {
	out := new(GetVResponse)
	err := c.cc.Invoke(ctx, "/store.StoreService/GetV", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) GetK(ctx context.Context, in *GetKRequest, opts ...grpc.CallOption) (*GetKResponse, error) {
	out := new(GetKResponse)
	err := c.cc.Invoke(ctx, "/store.StoreService/GetK", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) RemoveAll(ctx context.Context, in *RemoveAllRequest, opts ...grpc.CallOption) (*RemoveAllResponse, error) {
	out := new(RemoveAllResponse)
	err := c.cc.Invoke(ctx, "/store.StoreService/RemoveAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) StoreCsv(ctx context.Context, opts ...grpc.CallOption) (StoreService_StoreCsvClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StoreService_serviceDesc.Streams[0], "/store.StoreService/StoreCsv", opts...)
	if err != nil {
		return nil, err
	}
	x := &storeServiceStoreCsvClient{stream}
	return x, nil
}

type StoreService_StoreCsvClient interface {
	Send(*StoreCsvRequest) error
	CloseAndRecv() (*StoreCsvResponse, error)
	grpc.ClientStream
}

type storeServiceStoreCsvClient struct {
	grpc.ClientStream
}

func (x *storeServiceStoreCsvClient) Send(m *StoreCsvRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *storeServiceStoreCsvClient) CloseAndRecv() (*StoreCsvResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(StoreCsvResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storeServiceClient) RemoveCsv(ctx context.Context, opts ...grpc.CallOption) (StoreService_RemoveCsvClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StoreService_serviceDesc.Streams[1], "/store.StoreService/RemoveCsv", opts...)
	if err != nil {
		return nil, err
	}
	x := &storeServiceRemoveCsvClient{stream}
	return x, nil
}

type StoreService_RemoveCsvClient interface {
	Send(*RemoveCsvRequest) error
	CloseAndRecv() (*RemoveCsvResponse, error)
	grpc.ClientStream
}

type storeServiceRemoveCsvClient struct {
	grpc.ClientStream
}

func (x *storeServiceRemoveCsvClient) Send(m *RemoveCsvRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *storeServiceRemoveCsvClient) CloseAndRecv() (*RemoveCsvResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(RemoveCsvResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storeServiceClient) GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (StoreService_GetAllClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StoreService_serviceDesc.Streams[2], "/store.StoreService/GetAll", opts...)
	if err != nil {
		return nil, err
	}
	x := &storeServiceGetAllClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StoreService_GetAllClient interface {
	Recv() (*GetAllResponse, error)
	grpc.ClientStream
}

type storeServiceGetAllClient struct {
	grpc.ClientStream
}

func (x *storeServiceGetAllClient) Recv() (*GetAllResponse, error) {
	m := new(GetAllResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StoreServiceServer is the server API for StoreService service.
type StoreServiceServer interface {
	// Unary
	Store(context.Context, *StoreRequest) (*StoreResponse, error)
	Remove(context.Context, *RemoveRequest) (*RemoveResponse, error)
	GetV(context.Context, *GetVRequest) (*GetVResponse, error)
	GetK(context.Context, *GetKRequest) (*GetKResponse, error)
	RemoveAll(context.Context, *RemoveAllRequest) (*RemoveAllResponse, error)
	// client streaming
	StoreCsv(StoreService_StoreCsvServer) error
	RemoveCsv(StoreService_RemoveCsvServer) error
	// server streaming
	GetAll(*GetAllRequest, StoreService_GetAllServer) error
}

// UnimplementedStoreServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStoreServiceServer struct {
}

func (*UnimplementedStoreServiceServer) Store(ctx context.Context, req *StoreRequest) (*StoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Store not implemented")
}
func (*UnimplementedStoreServiceServer) Remove(ctx context.Context, req *RemoveRequest) (*RemoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Remove not implemented")
}
func (*UnimplementedStoreServiceServer) GetV(ctx context.Context, req *GetVRequest) (*GetVResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetV not implemented")
}
func (*UnimplementedStoreServiceServer) GetK(ctx context.Context, req *GetKRequest) (*GetKResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetK not implemented")
}
func (*UnimplementedStoreServiceServer) RemoveAll(ctx context.Context, req *RemoveAllRequest) (*RemoveAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveAll not implemented")
}
func (*UnimplementedStoreServiceServer) StoreCsv(srv StoreService_StoreCsvServer) error {
	return status.Errorf(codes.Unimplemented, "method StoreCsv not implemented")
}
func (*UnimplementedStoreServiceServer) RemoveCsv(srv StoreService_RemoveCsvServer) error {
	return status.Errorf(codes.Unimplemented, "method RemoveCsv not implemented")
}
func (*UnimplementedStoreServiceServer) GetAll(req *GetAllRequest, srv StoreService_GetAllServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}

func RegisterStoreServiceServer(s *grpc.Server, srv StoreServiceServer) {
	s.RegisterService(&_StoreService_serviceDesc, srv)
}

func _StoreService_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/store.StoreService/Store",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).Store(ctx, req.(*StoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/store.StoreService/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).Remove(ctx, req.(*RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_GetV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).GetV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/store.StoreService/GetV",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).GetV(ctx, req.(*GetVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_GetK_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).GetK(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/store.StoreService/GetK",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).GetK(ctx, req.(*GetKRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_RemoveAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).RemoveAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/store.StoreService/RemoveAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).RemoveAll(ctx, req.(*RemoveAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_StoreCsv_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StoreServiceServer).StoreCsv(&storeServiceStoreCsvServer{stream})
}

type StoreService_StoreCsvServer interface {
	SendAndClose(*StoreCsvResponse) error
	Recv() (*StoreCsvRequest, error)
	grpc.ServerStream
}

type storeServiceStoreCsvServer struct {
	grpc.ServerStream
}

func (x *storeServiceStoreCsvServer) SendAndClose(m *StoreCsvResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *storeServiceStoreCsvServer) Recv() (*StoreCsvRequest, error) {
	m := new(StoreCsvRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _StoreService_RemoveCsv_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StoreServiceServer).RemoveCsv(&storeServiceRemoveCsvServer{stream})
}

type StoreService_RemoveCsvServer interface {
	SendAndClose(*RemoveCsvResponse) error
	Recv() (*RemoveCsvRequest, error)
	grpc.ServerStream
}

type storeServiceRemoveCsvServer struct {
	grpc.ServerStream
}

func (x *storeServiceRemoveCsvServer) SendAndClose(m *RemoveCsvResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *storeServiceRemoveCsvServer) Recv() (*RemoveCsvRequest, error) {
	m := new(RemoveCsvRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _StoreService_GetAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetAllRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StoreServiceServer).GetAll(m, &storeServiceGetAllServer{stream})
}

type StoreService_GetAllServer interface {
	Send(*GetAllResponse) error
	grpc.ServerStream
}

type storeServiceGetAllServer struct {
	grpc.ServerStream
}

func (x *storeServiceGetAllServer) Send(m *GetAllResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _StoreService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "store.StoreService",
	HandlerType: (*StoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Store",
			Handler:    _StoreService_Store_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _StoreService_Remove_Handler,
		},
		{
			MethodName: "GetV",
			Handler:    _StoreService_GetV_Handler,
		},
		{
			MethodName: "GetK",
			Handler:    _StoreService_GetK_Handler,
		},
		{
			MethodName: "RemoveAll",
			Handler:    _StoreService_RemoveAll_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StoreCsv",
			Handler:       _StoreService_StoreCsv_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "RemoveCsv",
			Handler:       _StoreService_RemoveCsv_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetAll",
			Handler:       _StoreService_GetAll_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "storepb/store.proto",
}
